// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcyWqKMj4Usy_0cLOU1GJrstBnj0QON8k',
    appId: '1:72655689615:web:e4958f8bd876eb67cb5dfa',
    messagingSenderId: '72655689615',
    projectId: 'farmzo-1',
    authDomain: 'farmzo-1.firebaseapp.com',
    storageBucket: 'farmzo-1.firebasestorage.app',
    measurementId: 'G-EQSW5C8EDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP3D1iW0x66cL6q21A3AzfCQNsXrxx6D8',
    appId: '1:72655689615:android:55edee4ab4579b34cb5dfa',
    messagingSenderId: '72655689615',
    projectId: 'farmzo-1',
    storageBucket: 'farmzo-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpz7lXI1hYS3PGECldYzbMp9GiOHSHoo8',
    appId: '1:72655689615:ios:26b84555e52953c2cb5dfa',
    messagingSenderId: '72655689615',
    projectId: 'farmzo-1',
    storageBucket: 'farmzo-1.firebasestorage.app',
    iosBundleId: 'com.example.farmzo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpz7lXI1hYS3PGECldYzbMp9GiOHSHoo8',
    appId: '1:72655689615:ios:26b84555e52953c2cb5dfa',
    messagingSenderId: '72655689615',
    projectId: 'farmzo-1',
    storageBucket: 'farmzo-1.firebasestorage.app',
    iosBundleId: 'com.example.farmzo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcyWqKMj4Usy_0cLOU1GJrstBnj0QON8k',
    appId: '1:72655689615:web:a1a03f6ffc3b6f72cb5dfa',
    messagingSenderId: '72655689615',
    projectId: 'farmzo-1',
    authDomain: 'farmzo-1.firebaseapp.com',
    storageBucket: 'farmzo-1.firebasestorage.app',
    measurementId: 'G-DVRTTQPTXW',
  );
}
